services:
  startpage:
    container_name: startpage
    image: loganmarchione/docker-php-startpage:0.9.15@sha256:b6d4fdc45c0fddf9925a823cb30debce3456ff758582a625ba40e178a96800a6
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - 'user_includes:/var/www/html/user_includes'
    labels:
      - traefik.enable=true
      - traefik.http.routers.startpage.rule=Host(`startpage.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.startpage.tls=true
      - traefik.http.routers.startpage.tls.certresolver=cloudflare
      - traefik.http.routers.startpage.entrypoints=websecure
      - traefik.http.services.startpage.loadbalancer.server.port=80

networks:
  proxy:
    external: true

volumes:
  user_includes:
    driver: local
