services:
  startpage:
    container_name: startpage
    image: loganmarchione/docker-php-startpage:0.9.15@sha256:7f97a9483a6b61c4aac1888df22b7512d91e7749c5815d2d855a76420bce6be1
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - 'user_includes:/var/www/html/user_includes'
    labels:
      - traefik.enable=true
      - traefik.http.routers.startpage.rule=Host(`startpage.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.startpage.tls=true
      - traefik.http.routers.startpage.tls.certresolver=cloudflare
      - traefik.http.routers.startpage.entrypoints=websecure
      - traefik.http.services.startpage.loadbalancer.server.port=80

networks:
  proxy:
    external: true

volumes:
  user_includes:
    driver: local
