services:
  cyberchef:
    container_name: cyberchef
    image: ghcr.io/gchq/cyberchef:11.4.0@sha256:7630ff6e9928dfa22d02b5280ca8b8d39633942c366fac3b84f99f7e4f99acd8
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberchef.rule=Host(`cyberchef.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.cyberchef.tls=true
      - traefik.http.routers.cyberchef.tls.certresolver=cloudflare
      - traefik.http.routers.cyberchef.entrypoints=websecure
      - traefik.http.services.cyberchef.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
