services:
  cyberchef:
    container_name: cyberchef
    image: ghcr.io/gchq/cyberchef:11.3.0@sha256:58f68a92fb8e896028f0bb314e6cf5684c9551a84c0b0b2422450ee109b1e883
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberchef.rule=Host(`cyberchef.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.cyberchef.tls=true
      - traefik.http.routers.cyberchef.tls.certresolver=cloudflare
      - traefik.http.routers.cyberchef.entrypoints=websecure
      - traefik.http.services.cyberchef.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
