services:
  cyberchef:
    container_name: cyberchef
    image: ghcr.io/gchq/cyberchef:11.2.0@sha256:a150391b667ecf2626418fcecddfbfc0e8aebd671ef1ecdbb3be20fe9656f878
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.cyberchef.rule=Host(`cyberchef.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.cyberchef.tls=true
      - traefik.http.routers.cyberchef.tls.certresolver=cloudflare
      - traefik.http.routers.cyberchef.entrypoints=websecure
      - traefik.http.services.cyberchef.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
