services:
  influxdb:
    container_name: monitoring-influxdb
    image: influxdb:1.12.4@sha256:29e7c284e6de657a7145e11fbae20aa540c9ae3cb55923168bdf7bcfc4b57c7e
    restart: unless-stopped
    environment:
      - TZ=UTC
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - monitoring
    ports:
      - '0.0.0.0:8086:8086/tcp'  # All databases
      - '0.0.0.0:8089:8089/udp'  # Proxmox
      - '0.0.0.0:8090:8090/udp'  # Proxmox Backup Server
    volumes:
      - 'influx_config:/etc/influxdb'
      - 'influx_data:/var/lib/influxdb'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
  prometheus-server:
    container_name: monitoring-prometheus-server
    image: prom/prometheus:v3.12.0@sha256:69f5241418838263316593f7274a304b095c40bcf22e57272865da91bd60a8ac
    restart: unless-stopped
    environment:
      - TZ=UTC
    networks:
      - monitoring
      - proxy
    volumes:
      - 'prometheus_config:/etc/prometheus'
      - 'prometheus_data:/prometheus'
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=cloudflare
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
  telegraf-docker-host:
    container_name: monitoring-telegraf-docker-host
    image: telegraf:1.39.0-alpine@sha256:dcad79e7e0fd1d28b058785bed296b5bf17465105ef0545f20df901003f97d59
    restart: unless-stopped
    environment:
      - TZ=UTC
      - HOST_PROC=/host/proc
    user: telegraf:997  # This needs to be the group id of running `stat -c '%g' /var/run/docker.sock` on the docker host
    networks:
      - monitoring
    depends_on:
      - influxdb
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/proc:/host/proc:ro'
      - 'telegraf_docker_host:/etc/telegraf:ro'
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - SETFCAP
      - SETPCAP
      - SETGID
      - SETUID
  telegraf-whois:
    container_name: monitoring-telegraf-whois
    image: telegraf:1.39.0-alpine@sha256:dcad79e7e0fd1d28b058785bed296b5bf17465105ef0545f20df901003f97d59
    restart: unless-stopped
    environment:
      - TZ=UTC
    networks:
      - monitoring
    depends_on:
      - influxdb
    volumes:
      - 'telegraf_whois:/etc/telegraf:ro'
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETPCAP
      - SETGID
      - SETUID
  telegraf-x509:
    container_name: monitoring-telegraf-x509
    image: telegraf:1.39.0-alpine@sha256:dcad79e7e0fd1d28b058785bed296b5bf17465105ef0545f20df901003f97d59
    restart: unless-stopped
    environment:
      - TZ=UTC
    networks:
      - monitoring
    depends_on:
      - influxdb
    volumes:
      - 'telegraf_x509:/etc/telegraf:ro'
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETPCAP
      - SETGID
      - SETUID
  grafana:
    container_name: monitoring-grafana
    image: grafana/grafana-oss:13.0.2@sha256:5dad0df181cb644a14e13617b913b261a54f7d4fd4510721dba420929f35bea2
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:
      - /custom/files/grafana.env
    networks:
      - proxy
      - monitoring
    depends_on:
      - influxdb
    volumes:
      - 'grafana_data:/var/lib/grafana'
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=cloudflare
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  monitoring:
  proxy:
    external: true

volumes:
  influx_config:
    driver: local
  influx_data:
    driver: local
  prometheus_config:
    driver: local
  prometheus_data:
    driver: local
  telegraf_docker_host:
    driver: local
  telegraf_whois:
    driver: local
  telegraf_x509:
    driver: local
  grafana_data:
    driver: local
