services:
  postgres:
    container_name: forgejo-postgres
    image: postgres:17.10-alpine@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:
      - /custom/files/forgejo.env
    networks:
      - forgejo
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "forgejo"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:15.0.4-rootless@sha256:aea6847e7e18130f173616a92433e47e00813bbe7b42e3732cbbb5f237164096
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/forgejo.env
    networks:
      - forgejo
      - proxy
    depends_on:
      - postgres
    volumes:
      - 'forgejo_config:/etc/gitea'
      - 'forgejo_data:/var/lib/gitea'
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`forgejo.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.forgejo.tls=true
      - traefik.http.routers.forgejo.tls.certresolver=cloudflare
      - traefik.http.routers.forgejo.entrypoints=websecure
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  forgejo:
  proxy:
    external: true

volumes:
  forgejo_config:
    driver: local
  forgejo_data:
    driver: local
  postgres_data:
    driver: local
