services:
  postgres:
    container_name: forgejo-postgres
    image: postgres:17.11-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:
      - /custom/files/forgejo.env
    networks:
      - forgejo
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "forgejo"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:16.0.2-rootless@sha256:23ccc146e6dc2cd1f5c5435909baae64db873201717f1726490dae649283e6cd
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/forgejo.env
    networks:
      - forgejo
      - proxy
    depends_on:
      - postgres
    volumes:
      - 'forgejo_config:/etc/gitea'
      - 'forgejo_data:/var/lib/gitea'
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`forgejo.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.forgejo.tls=true
      - traefik.http.routers.forgejo.tls.certresolver=cloudflare
      - traefik.http.routers.forgejo.entrypoints=websecure
      - traefik.http.services.forgejo.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  forgejo:
  proxy:
    external: true

volumes:
  forgejo_config:
    driver: local
  forgejo_data:
    driver: local
  postgres_data:
    driver: local
