services:
  postgres:
    container_name: forgejo-postgres
    image: postgres:17.9-alpine@sha256:778d0b486d6daa02b77434d0358ec57a1b21fd8b6d22ac2eef56a33e816928f6
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:
      - /custom/files/forgejo.env
    networks:
      - forgejo
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "forgejo"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:15.0.0-rootless@sha256:ab6ca32ae0d5af2494b77aa22dd5cd2f24087f4325b396d09188b695ce004e24
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/forgejo.env
    networks:
      - forgejo
      - proxy
    depends_on:
      - postgres
    volumes:
      - 'forgejo_config:/etc/gitea'
      - 'forgejo_data:/var/lib/gitea'
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.rule=Host(`forgejo.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.forgejo.tls=true
      - traefik.http.routers.forgejo.tls.certresolver=cloudflare
      - traefik.http.routers.forgejo.entrypoints=websecure
      - traefik.http.services.forgejo.loadbalancer.server.port=3000

networks:
  forgejo:
  proxy:
    external: true

volumes:
  forgejo_config:
    driver: local
  forgejo_data:
    driver: local
  postgres_data:
    driver: local
