services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.27.3@sha256:87a67ee09d3ae0d1df5fda5dcda3e2a1f9236a45b0a59025d6e00e46adc43bef
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - USER_UID=5000
      - USER_GID=5000
    networks:
      - proxy
    volumes:
      - 'gitea_new_data:/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.git.rule=Host(`git.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.git.tls=true
      - traefik.http.routers.git.tls.certresolver=cloudflare
      - traefik.http.routers.git.entrypoints=websecure
      - traefik.http.services.git.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
  gitea-runner:
    container_name: gitea-runner
    image: gitea/runner:3.3.1@sha256:c8570d703deb1bbe53c7e203092cfc5a310ca074559dc7fe2e7ebe11dd066577
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - CONFIG_FILE=/gitea_runner_config/config.yaml
      - GITEA_INSTANCE_URL=https://gitea.${SECRET_INTERNAL_DOMAIN_NAME}
      - GITEA_RUNNER_NAME=runner1
    env_file:
      - /custom/files/gitea_runner.env
    networks:
      - proxy
    depends_on:
      - gitea
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'gitea_runner_data:/data'
      - 'gitea_runner_config:/gitea_runner_config'
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true

volumes:
  gitea_new_data:
    driver: local
  gitea_runner_config:
    driver: local
  gitea_runner_data:
    driver: local
