services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.26.0@sha256:af07b88edbb2173d20932f9c75ebcf4e61d7d5c2d6a7ab5cc6b97cba28aea352
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - USER_UID=5000
      - USER_GID=5000
    networks:
      - proxy
    volumes:
      - 'gitea_new_data:/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.git.rule=Host(`git.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.git.tls=true
      - traefik.http.routers.git.tls.certresolver=cloudflare
      - traefik.http.routers.git.entrypoints=websecure
      - traefik.http.services.git.loadbalancer.server.port=3000
  gitea-runner:
    container_name: gitea-runner
    image: gitea/act_runner:0.3.1@sha256:c2a169c5e99864c25e32527cef3d82203225e09558773022bf3dc164a2e6d762
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - CONFIG_FILE=/gitea_runner_config/config.yaml
      - GITEA_INSTANCE_URL=https://gitea.${SECRET_INTERNAL_DOMAIN_NAME}
      - GITEA_RUNNER_NAME=runner1
    env_file:
      - /custom/files/gitea_runner.env
    networks:
      - proxy
    depends_on:
      - gitea
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'gitea_runner_data:/data'
      - 'gitea_runner_config:/gitea_runner_config'

networks:
  proxy:
    external: true

volumes:
  gitea_new_data:
    driver: local
  gitea_runner_config:
    driver: local
  gitea_runner_data:
    driver: local
