services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.26.4@sha256:8e25c717b8f748445e15ec46e0390f577cb628101184cb0a150d1dae126c1f39
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - USER_UID=5000
      - USER_GID=5000
    networks:
      - proxy
    volumes:
      - 'gitea_new_data:/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.git.rule=Host(`git.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.git.tls=true
      - traefik.http.routers.git.tls.certresolver=cloudflare
      - traefik.http.routers.git.entrypoints=websecure
      - traefik.http.services.git.loadbalancer.server.port=3000
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
  gitea-runner:
    container_name: gitea-runner
    image: gitea/runner:1.0.0@sha256:2198bd3bf2d31059ecd27e845569aa4d666f26d15a0a3cc9abb85898368a0eab
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - CONFIG_FILE=/gitea_runner_config/config.yaml
      - GITEA_INSTANCE_URL=https://gitea.${SECRET_INTERNAL_DOMAIN_NAME}
      - GITEA_RUNNER_NAME=runner1
    env_file:
      - /custom/files/gitea_runner.env
    networks:
      - proxy
    depends_on:
      - gitea
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'gitea_runner_data:/data'
      - 'gitea_runner_config:/gitea_runner_config'
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true

volumes:
  gitea_new_data:
    driver: local
  gitea_runner_config:
    driver: local
  gitea_runner_data:
    driver: local
