services:
  dokuwiki:
    container_name: dokuwiki
    image: php:8.4-apache-bookworm@sha256:1ff6421ba0d3b429c465d2fdc694efad660e64e46857e7cb9a0415c5c3308b87
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    volumes:
      - 'dokuwiki_config:/var/www/html'
      - 'php_config:/usr/local/etc/php'
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`wiki.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.wiki.tls=true
      - traefik.http.routers.wiki.tls.certresolver=cloudflare
      - traefik.http.routers.wiki.entrypoints=websecure
      - traefik.http.services.wiki.loadbalancer.server.port=80

networks:
  proxy:
    external: true

volumes:
  dokuwiki_config:
    driver: local
  php_config:
    driver: local
