services:
  postfixrelay:
    container_name: postfixrelay
    image: loganmarchione/docker-postfixrelay:1.6.2@sha256:ee469f4a416fc4aa04d51a9d6610a1a7d9ed8f3b60e4cce35edb9a8fd7da08df
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/postfixrelay.env
    networks:
      - proxy  # This is needed in order for Drone to talk to Postfix, they just needed to be on the same network and this hack worked
    ports:
      - '0.0.0.0:25:25/tcp'
    volumes:
      - 'postfixrelay_data:/var/spool/postfix'

networks:
  proxy:
    external: true

volumes:
  postfixrelay_data:
    driver: local
