services:
  postfixrelay:
    container_name: postfixrelay
    image: loganmarchione/docker-postfixrelay:1.6.2@sha256:4e6ea65b2d2b73efb7d040190725ca2f152001a5e039512f5626c842e6582cbe
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/postfixrelay.env
    networks:
      - proxy  # This is needed in order for Drone to talk to Postfix, they just needed to be on the same network and this hack worked
    ports:
      - '0.0.0.0:25:25/tcp'
    volumes:
      - 'postfixrelay_data:/var/spool/postfix'
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

networks:
  proxy:
    external: true

volumes:
  postfixrelay_data:
    driver: local
