services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:2.3.3@sha256:49d7b60987616387c306a8023087b31f2c9b7b21288b523026cb04058e8b6dbb
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/miniflux.env
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.miniflux.rule=Host(`miniflux.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.miniflux.tls=true
      - traefik.http.routers.miniflux.tls.certresolver=cloudflare
      - traefik.http.routers.miniflux.entrypoints=websecure
      - traefik.http.services.miniflux.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
