services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist:v0.5.11@sha256:f7bfd5cc8d9931c752d07206f082440a56d88eec595a0a5d684dce762b402d64
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/tubearchivist.env
    networks:
      - proxy
      - tubearchivist
    depends_on:
      - tubearchivist-elasticsearch
      - tubearchivist-redis
    volumes:
      - 'tubearchivist_cache:/cache'
      # The directory below is huge, so storing it on the NAS
      - '/custom_mounts/media/library/YouTube:/youtube'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.tubearchivist.rule=Host(`tubearchivist.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.tubearchivist.tls=true
      - traefik.http.routers.tubearchivist.tls.certresolver=cloudflare
      - traefik.http.routers.tubearchivist.entrypoints=websecure
      - traefik.http.services.tubearchivist.loadbalancer.server.port=8000
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
  tubearchivist-redis:
    container_name: tubearchivist-redis
    image: redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
    restart: unless-stopped
    networks:
      - tubearchivist
    depends_on:
      - tubearchivist-elasticsearch
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - SETPCAP
  tubearchivist-elasticsearch:
    container_name: tubearchivist-elasticsearch
    image: elasticsearch:8.19.20@sha256:7c6a3d514563848873ae3e0e2e36502382842ebae38134a59e91214e8fcdabf3
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:
      - /custom/files/tubearchivist.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - tubearchivist
    volumes:
      - 'elasticsearch_data:/usr/share/elasticsearch/data'
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f -u elastic:$${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health?pretty | grep -q '\"status\" : \"green\"\\|\"status\" : \"yellow\"'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  tubearchivist:
  proxy:
    external: true

volumes:
  tubearchivist_cache:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
