services:
  kiwix:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:12df8dc8fb6d030af38e7733e846d4f4c9a0eb3302777e4e2e52337bf86e2fb7
    command:
      - '*.zim'
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    volumes:
      - '/custom_mounts/media_nc/library/Kiwix:/data:ro'
    labels:
      - traefik.enable=true
      - traefik.http.routers.kiwix.rule=Host(`kiwix.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.kiwix.tls=true
      - traefik.http.routers.kiwix.tls.certresolver=cloudflare
      - traefik.http.routers.kiwix.entrypoints=websecure
      - traefik.http.services.kiwix.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
