services:
  kiwix:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:3.8.2@sha256:7431be257ac0b0b6f14633ef088774f6d5122246940b594b3017a70169058b08
    command:
      - '*.zim'
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    volumes:
      - '/custom_mounts/media_nc/library/Kiwix:/data:ro'
    labels:
      - traefik.enable=true
      - traefik.http.routers.kiwix.rule=Host(`kiwix.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.kiwix.tls=true
      - traefik.http.routers.kiwix.tls.certresolver=cloudflare
      - traefik.http.routers.kiwix.entrypoints=websecure
      - traefik.http.services.kiwix.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
