services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.45.0-alpine@sha256:e6b0225f4bbc989e398c85062f7426f8cf4b61f8aca6f40bf44789d1dada1949
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
      - proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.scheme=https
      - traefik.http.services.portainer.loadbalancer.server.port=9443
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true

volumes:
  portainer_data:
    driver: local
