services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    group_add:
      - '106'  # This needs to be the group id of running `stat -c '%g' /dev/dri/renderD128` on the docker host
    networks:
      - proxy
    volumes:
      - 'jellyfin_config:/config'
      - 'jellyfin_cache:/cache'
      - '/custom_mounts/media:/custom_mounts/media:ro'
      - '/custom_mounts/media_nc:/custom_mounts/media_nc:ro'
    devices:
      - '/dev/dri/:/dev/dri/'
      - '/dev/dri/renderD128:/dev/dri/renderD128'
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true

volumes:
  jellyfin_config:
    driver: local
  jellyfin_cache:
    driver: local
