services:
  webdav:
    container_name: webdav
    image: loganmarchione/docker-webdav-nginx:1.1.0@sha256:cb6590422fc04c1656a2d25a04a904338cd3b135158ebf7d452f7c018a277dc8
    restart: unless-stopped
    env_file:
      - /custom/files/webdav.env
    networks:
      - proxy
    volumes:
      - 'webdav:/var/www/webdav'
    labels:
      - traefik.enable=true
      - traefik.http.routers.webdav.rule=Host(`webdav.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.webdav.tls=true
      - traefik.http.routers.webdav.tls.certresolver=cloudflare
      - traefik.http.routers.webdav.entrypoints=websecure
      - traefik.http.services.webdav.loadbalancer.server.port=80
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

networks:
  proxy:
    external: true

volumes:
  webdav:
    driver: local
