services:
  webdav:
    container_name: webdav
    image: loganmarchione/docker-webdav-nginx:1.1.0@sha256:2850390174fcba3c28e3d49302f9ae0bb72e59d99a4c11c07d1a22655f483fae
    restart: unless-stopped
    env_file:
      - /custom/files/webdav.env
    networks:
      - proxy
    volumes:
      - 'webdav:/var/www/webdav'
    labels:
      - traefik.enable=true
      - traefik.http.routers.webdav.rule=Host(`webdav.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.webdav.tls=true
      - traefik.http.routers.webdav.tls.certresolver=cloudflare
      - traefik.http.routers.webdav.entrypoints=websecure
      - traefik.http.services.webdav.loadbalancer.server.port=80
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

networks:
  proxy:
    external: true

volumes:
  webdav:
    driver: local
