services:
  webdav:
    container_name: webdav
    image: loganmarchione/docker-webdav-nginx:1.1.0@sha256:37e519421d0454cb8f626341db750ea0cd6f04fde62b5c9a143087d6e5d57b91
    restart: unless-stopped
    env_file:
      - /custom/files/webdav.env
    networks:
      - proxy
    volumes:
      - 'webdav:/var/www/webdav'
    labels:
      - traefik.enable=true
      - traefik.http.routers.webdav.rule=Host(`webdav.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.webdav.tls=true
      - traefik.http.routers.webdav.tls.certresolver=cloudflare
      - traefik.http.routers.webdav.entrypoints=websecure
      - traefik.http.services.webdav.loadbalancer.server.port=80

networks:
  proxy:
    external: true

volumes:
  webdav:
    driver: local
