services:
  planka:
    container_name: planka
    image: ghcr.io/plankanban/planka:2.1.1@sha256:c872f1dd5bbfabb1ea355fbc2a3dd0346d87c20c16394f601c24093fbbe6e0cb
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/planka.env
    networks:
      - proxy
    volumes:
      - 'planka_data:/app/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.planka.rule=Host(`planka.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.planka.tls=true
      - traefik.http.routers.planka.tls.certresolver=cloudflare
      - traefik.http.routers.planka.entrypoints=websecure
      - traefik.http.services.planka.loadbalancer.server.port=1337

networks:
  proxy:
    external: true

volumes:
  planka_data:
    driver: local
