services:
  planka:
    container_name: planka
    image: ghcr.io/plankanban/planka:2.2.1@sha256:125f45330853210c678fed1132bedc0912b4a11a27779b79802fbca108e069e2
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/planka.env
    networks:
      - proxy
    volumes:
      - 'planka_data:/app/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.planka.rule=Host(`planka.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.planka.tls=true
      - traefik.http.routers.planka.tls.certresolver=cloudflare
      - traefik.http.routers.planka.entrypoints=websecure
      - traefik.http.services.planka.loadbalancer.server.port=1337
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true

volumes:
  planka_data:
    driver: local
