services:
  planka:
    container_name: planka
    image: ghcr.io/plankanban/planka:2.1.0@sha256:32c919d9e65b0479d1bbf0e4fb8e00fb11403a5234242b9f5fc900e595c2e2ce
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/planka.env
    networks:
      - proxy
    volumes:
      - 'planka_data:/app/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.planka.rule=Host(`planka.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.planka.tls=true
      - traefik.http.routers.planka.tls.certresolver=cloudflare
      - traefik.http.routers.planka.entrypoints=websecure
      - traefik.http.services.planka.loadbalancer.server.port=1337

networks:
  proxy:
    external: true

volumes:
  planka_data:
    driver: local
