services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v3.14.0@sha256:b9fac07e6daaabd8c29d0dc97965c2f500ce7d6b188b0c51f494627f23ad32f2
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/mealie.env
    networks:
      - proxy
    volumes:
      - 'mealie_data:/app/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`recipes.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.mealie.tls=true
      - traefik.http.routers.mealie.tls.certresolver=cloudflare
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.http.services.mealie.loadbalancer.server.port=9000

networks:
  proxy:
    external: true

volumes:
  mealie_data:
    driver: local
