services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v3.13.1@sha256:4ee2b9e807627fac79eb7509bbf6577271747346e3d16208a0de939276ccaac2
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/mealie.env
    networks:
      - proxy
    volumes:
      - 'mealie_data:/app/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`recipes.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.mealie.tls=true
      - traefik.http.routers.mealie.tls.certresolver=cloudflare
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.http.services.mealie.loadbalancer.server.port=9000

networks:
  proxy:
    external: true

volumes:
  mealie_data:
    driver: local
