services:
  spdf:
    container_name: spdf
    image: ghcr.io/stirling-tools/s-pdf:2.14.2@sha256:7ed4d9681d18e4fbc3aa6a63647c4b5c2bcc4b75841df7c05d7e3d2320f5c9a1
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - SYSTEM_ENABLEANALYTICS=false
      - SECURITY_ENABLELOGIN=false
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.spdf.rule=Host(`spdf.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.spdf.tls=true
      - traefik.http.routers.spdf.tls.certresolver=cloudflare
      - traefik.http.routers.spdf.entrypoints=websecure
      - traefik.http.services.spdf.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

networks:
  proxy:
    external: true
