services:
  spdf:
    container_name: spdf
    image: ghcr.io/stirling-tools/s-pdf:3.0.2@sha256:c195925341aa35ee5932d9c225edef48a92e46a1280963180d79619cb5f29e6e
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - SYSTEM_ENABLEANALYTICS=false
      - SECURITY_ENABLELOGIN=false
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.spdf.rule=Host(`spdf.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.spdf.tls=true
      - traefik.http.routers.spdf.tls.certresolver=cloudflare
      - traefik.http.routers.spdf.entrypoints=websecure
      - traefik.http.services.spdf.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

networks:
  proxy:
    external: true
