services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:31.0.2@sha256:a3384902221ca45e14678b64b1026154331bf498000d37215b5bb0cf0b2c222b
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - DRAWIO_BASE_URL=https://drawio.${SECRET_INTERNAL_DOMAIN_NAME}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=Host(`drawio.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.drawio.tls=true
      - traefik.http.routers.drawio.tls.certresolver=cloudflare
      - traefik.http.routers.drawio.entrypoints=websecure
      - traefik.http.services.drawio.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
