services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:30.2.6@sha256:0459cc8b57be47b2f8eb51393899610e2bfcb5bf468a47fdf1971e23571d26ff
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - DRAWIO_BASE_URL=https://drawio.${SECRET_INTERNAL_DOMAIN_NAME}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=Host(`drawio.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.drawio.tls=true
      - traefik.http.routers.drawio.tls.certresolver=cloudflare
      - traefik.http.routers.drawio.entrypoints=websecure
      - traefik.http.services.drawio.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
