services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:31.1.8@sha256:6d13a8d6cee6048e8eb8c1d104753e8902cd84e9395d26ead04be4ee7f7a60c3
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - DRAWIO_BASE_URL=https://drawio.${SECRET_INTERNAL_DOMAIN_NAME}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=Host(`drawio.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.drawio.tls=true
      - traefik.http.routers.drawio.tls.certresolver=cloudflare
      - traefik.http.routers.drawio.entrypoints=websecure
      - traefik.http.services.drawio.loadbalancer.server.port=8080
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

networks:
  proxy:
    external: true
